'*.{ts,tsx,js}':
  - eslint --cache --cache-location ./node_modules/.cache/.eslintcache --fix
  - prettier --log-level warn --cache --write
'*.{json,yml}':
  - prettier --log-level warn --cache --write
